document.addEventListener('DOMContentLoaded', () => {
        const wordDisplay = document.getElementById('word-display');
            const clueDisplay = document.getElementById('clue-display');
                const keyboard = document.getElementById('keyboard');
                    const messageArea = document.getElementById('message-area');
                        const restartButton = document.getElementById('restart-button');
                            const forcaImg = document.getElementById('forca-img');

                                const words = [
                                        { word: "JAVASCRIPT", clue: "Linguagem de programação para web" },
                                                { word: "HTML", clue: "Linguagem de marcação para estrutura de páginas" },
                                                        { word: "CSS", clue: "Linguagem de estilo para visual da página" },
                                                                { word: "FORCASERRINHA", clue: "Nome do nosso jogo" },
                                                                        { word: "PROGRAMACAO", clue: "Arte de escrever código" },
                                                                            ];

                                                                                let selectedWord = '';
                                                                                    let selectedClue = '';
                                                                                        let guessedLetters = [];
                                                                                            let mistakes = 0;
                                                                                                const maxMistakes = 6;

                                                                                                    function startGame() {
                                                                                                            const randomIndex = Math.floor(Math.random() * words.length);
                                                                                                                    selectedWord = words[randomIndex].word;
                                                                                                                            selectedClue = words[randomIndex].clue;
                                                                                                                                    guessedLetters = [];
                                                                                                                                            mistakes = 0;
                                                                                                                                                    messageArea.textContent = '';
                                                                                                                                                            restartButton.style.display = 'none';
                                                                                                                                                                    forcaImg.src = `images/forca_${mistakes}.png`; // Garanta que você tenha imagens de forca_0.png a forca_6.png

                                                                                                                                                                            displayWord();
                                                                                                                                                                                    displayClue();
                                                                                                                                                                                            createKeyboard();
                                                                                                                                                                                                }

                                                                                                                                                                                                    function displayWord() {
                                                                                                                                                                                                            wordDisplay.innerHTML = selectedWord.split('').map(letter => {
                                                                                                                                                                                                                        return `<span>${guessedLetters.includes(letter) ? letter : '_'}</span>`;
                                                                                                                                                                                                                                }).join('');
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                        function displayClue() {
                                                                                                                                                                                                                                                clueDisplay.textContent = `Dica: ${selectedClue}`;
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                        function createKeyboard() {
                                                                                                                                                                                                                                                                keyboard.innerHTML = '';
                                                                                                                                                                                                                                                                        for (let i = 65; i <= 90; i++) {
                                                                                                                                                                                                                                                                                    const letter = String.fromCharCode(i);
                                                                                                                                                                                                                                                                                                const button = document.createElement('button');
                                                                                                                                                                                                                                                                                                            button.textContent = letter;
                                                                                                                                                                                                                                                                                                                        button.classList.add('key-button');
                                                                                                                                                                                                                                                                                                                                    button.addEventListener('click', () => handleGuess(letter, button));
                                                                                                                                                                                                                                                                                                                                                keyboard.appendChild(button);
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                function handleGuess(letter, button) {
                                                                                                                                                                                                                                                                                                                                                                        if (guessedLetters.includes(letter) || mistakes >= maxMistakes) return;

                                                                                                                                                                                                                                                                                                                                                                                guessedLetters.push(letter);
                                                                                                                                                                                                                                                                                                                                                                                        button.disabled = true;

                                                                                                                                                                                                                                                                                                                                                                                                if (selectedWord.includes(letter)) {
                                                                                                                                                                                                                                                                                                                                                                                                            displayWord();
                                                                                                                                                                                                                                                                                                                                                                                                                        checkWin();
                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                            mistakes++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        forcaImg.src = `images/forca_${mistakes}.png`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    checkLoss();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function checkWin() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const currentWord = wordDisplay.textContent.replace(/_/g, '').replace(/\s/g, '');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (currentWord === selectedWord) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                messageArea.textContent = 'Parabéns! Você venceu!';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            endGame();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function checkLoss() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (mistakes >= maxMistakes) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                messageArea.textContent = `Você perdeu! A palavra era: ${selectedWord}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            endGame();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function endGame() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const buttons = keyboard.querySelectorAll('.key-button');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            buttons.forEach(button => button.disabled = true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    restartButton.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            restartButton.addEventListener('click', startGame);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Inicializa o jogo ao carregar a página
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    startGame();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
})