document.addEventListener('DOMContentLoaded', () => {
        const webButton = document.getElementById('web-button');
            const webArea = document.getElementById('web-effect-area');

                if (webButton && webArea) {
                        webButton.addEventListener('click', () => {
                                    // Obtém a posição e o tamanho do botão
                                                const buttonRect = webButton.getBoundingClientRect();
                                                            // Calcula o centro do botão em relação à *janela de visualização*
                                                                        const startX = buttonRect.left + buttonRect.width / 2;
                                                                                    const startY = buttonRect.top + buttonRect.height / 2;
                                                                                                
                                                                                                            // Remove quaisquer teias antigas antes de criar novas (não necessário se elas se removem sozinhas, mas é bom para garantir)
                                                                                                                        // webArea.innerHTML = '';
                                                                                                                                    
                                                                                                                                                // Cria 8 linhas de teia
                                                                                                                                                            const numberOfLines = 8;
                                                                                                                                                                        
                                                                                                                                                                                    for (let i = 0; i < numberOfLines; i++) {
                                                                                                                                                                                                    // 1. Cria o elemento div para a linha
                                                                                                                                                                                                                    const line = document.createElement('div');
                                                                                                                                                                                                                                    line.classList.add('web-line');
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                    // 2. Define a posição inicial no centro do botão (em relação à *janela*)
                                                                                                                                                                                                                                                                                    line.style.left = `${startX}px`;
                                                                                                                                                                                                                                                                                                    line.style.top = `${startY}px`;
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                    // 3. Define um ângulo aleatório (0 a 360 graus)
                                                                                                                                                                                                                                                                                                                                                    const angle = Math.random() * 360;
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                    // 4. Define um comprimento e atraso aleatórios
                                                                                                                                                                                                                                                                                                                                                                                                    const length = Math.random() * 300 + 100; // Comprimento entre 100px e 400px
                                                                                                                                                                                                                                                                                                                                                                                                                    const delay = i * 0.05;

                                                                                                                                                                                                                                                                                                                                                                                                                                    // 5. Aplica a rotação e o comprimento (inicialmente 0 para a animação)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Usamos scaleX(0) para a animação de esticar. O CSS usa transform-origin: left.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line.style.transform = `rotate(${angle}deg) scaleX(0)`; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line.style.transitionDelay = `${delay}s`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Anexa ao corpo, pois as linhas estão posicionadas absolutamente em relação à janela.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Se elas estivessem dentro de webArea, a posição deveria ser relativa ao contêiner.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.body.appendChild(line);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 6. Força o reflow para garantir que a transição funcione
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    void line.offsetWidth;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 7. Define o estado final (animação)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // scaleX faz a linha esticar. O 1.05 é para garantir que a linha cubra a origem.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // O opacity 0 faz a linha desaparecer.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line.style.transform = `rotate(${angle}deg) scaleX(${length / 3}) translateX(3px)`; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line.style.opacity = 0; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Remove o elemento após a animação (duração + atraso)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line.remove();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 1000 + (delay * 1000)); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error("Elementos 'web-button' ou 'web-effect-area' não encontrados.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
})