document.addEventListener('DOMContentLoaded', () => {
        console.log("Site anti-fake news carregado com sucesso!");

            // --- Elementos do Modal e Botão ---
                const modal = document.getElementById("quiz-modal");
                    const btn = document.getElementById("btn-quiz");
                        const span = document.getElementsByClassName("close-btn")[0];

                            // --- Lógica do Quiz ---
                                const quizData = [
                                        {
                                                    pergunta: "Qual é o primeiro passo para checar a veracidade de uma notícia?",
                                                                opcoes: [
                                                                                { texto: "Compartilhar imediatamente para alertar os amigos.", correta: false },
                                                                                                { texto: "Verificar a fonte: o site e o autor são conhecidos e confiáveis?", correta: true },
                                                                                                                { texto: "Apenas ler o título, se for chocante, deve ser verdade.", correta: false }
                                                                                                                            ]
                                                                                                                                    },
                                                                                                                                            {
                                                                                                                                                        pergunta: "Qual é um dos principais objetivos dos criadores de Fake News?",
                                                                                                                                                                    opcoes: [
                                                                                                                                                                                    { texto: "Promover a saúde e o bem-estar social.", correta: false },
                                                                                                                                                                                                    { texto: "Gerar cliques para ganho financeiro ou influenciar a opinião pública.", correta: true },
                                                                                                                                                                                                                    { texto: "Garantir a precisão e a imparcialidade jornalística.", correta: false }
                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                // Adicione mais perguntas aqui!
                                                                                                                                                                                                                                                    ];

                                                                                                                                                                                                                                                        let currentQuestionIndex = 0;
                                                                                                                                                                                                                                                            const quizPergunta = document.getElementById('quiz-pergunta');
                                                                                                                                                                                                                                                                const quizOpcoes = document.getElementById('quiz-opcoes');
                                                                                                                                                                                                                                                                    const quizFeedback = document.getElementById('quiz-feedback');

                                                                                                                                                                                                                                                                        // Função para carregar uma nova pergunta
                                                                                                                                                                                                                                                                            function loadQuiz() {
                                                                                                                                                                                                                                                                                    if (currentQuestionIndex < quizData.length) {
                                                                                                                                                                                                                                                                                                const currentQuiz = quizData[currentQuestionIndex];
                                                                                                                                                                                                                                                                                                            quizPergunta.textContent = `Pergunta ${currentQuestionIndex + 1}: ${currentQuiz.pergunta}`;
                                                                                                                                                                                                                                                                                                                        quizOpcoes.innerHTML = ''; // Limpa opções anteriores
                                                                                                                                                                                                                                                                                                                                    quizFeedback.textContent = ''; // Limpa feedback

                                                                                                                                                                                                                                                                                                                                                currentQuiz.opcoes.forEach(opcao => {
                                                                                                                                                                                                                                                                                                                                                                const button = document.createElement('button');
                                                                                                                                                                                                                                                                                                                                                                                button.classList.add('quiz-opcao');
                                                                                                                                                                                                                                                                                                                                                                                                button.textContent = opcao.texto;
                                                                                                                                                                                                                                                                                                                                                                                                                button.dataset.correta = opcao.correta;
                                                                                                                                                                                                                                                                                                                                                                                                                                button.addEventListener('click', checkAnswer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                quizOpcoes.appendChild(button);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Fim do Quiz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quizPergunta.textContent = "Parabéns! Você concluiu o Quiz da Verdade.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        quizOpcoes.innerHTML = '<p>Seu olhar crítico é essencial para uma sociedade informada.</p>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    quizFeedback.textContent = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Função para checar a resposta
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function checkAnswer(event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const selectedButton = event.target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const isCorrect = selectedButton.dataset.correta === "true";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Desabilita os botões para evitar cliques duplos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Array.from(quizOpcoes.children).forEach(button => button.disabled = true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (isCorrect) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quizFeedback.textContent = "✅ Certo! Próxima pergunta...";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        selectedButton.style.backgroundColor = '#4CAF50'; // Verde
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quizFeedback.textContent = "❌ Errado. Lembre-se de sempre verificar a fonte primeiro.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        selectedButton.style.backgroundColor = '#ff4500'; // Vermelho
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Avança para a próxima pergunta após um pequeno delay
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentQuestionIndex++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        loadQuiz();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, 1500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // --- Eventos de Modal ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Quando o usuário clica no botão, abre o modal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btn.onclick = function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        currentQuestionIndex = 0; // Reseta o quiz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loadQuiz();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        modal.style.display = "block";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Quando o usuário clica no (x), fecha o modal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    span.onclick = function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modal.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Quando o usuário clica fora do modal, fecha
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.onclick = function(event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (event.target == modal) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modal.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
})