document.addEventListener("DOMContentLoaded", () => {

        const header = document.querySelector("header");
            const nav = document.querySelector("nav");
                const links = document.querySelectorAll("nav a");
                    const spans = document.querySelectorAll("nav span");
                        const main = document.querySelector("main");
                            const section = document.querySelector("section");
                                const divCards = document.querySelector(".cards");
                                    const articles = document.querySelectorAll("article");
                                        const figures = document.querySelectorAll("figure");
                                            const images = document.querySelectorAll("img");
                                                const aside = document.querySelector("aside");
                                                    const footer = document.querySelector("footer");
                                                        const tables = document.querySelectorAll("table");
                                                            const lists = document.querySelectorAll("ul, ol");

                                                                if (header) {
                                                                        header.addEventListener("click", () => {
                                                                                    header.style.backgroundColor = "#1abc9c";
                                                                                            });
                                                                                                }

                                                                                                    links.forEach(link => {
                                                                                                            link.addEventListener("click", (event) => {
                                                                                                                        event.preventDefault();
                                                                                                                                    links.forEach(l => l.classList.remove("ativo"));
                                                                                                                                                link.classList.add("ativo");
                                                                                                                                                        });
                                                                                                                                                            });
                                                                                                                                                                });

                                                                                                                                                                    spans.forEach(span => {
                                                                                                                                                                            span.addEventListener("mouseover", () => {
                                                                                                                                                                                        span.style.textDecoration = "underline";
                                                                                                                                                                                                });
                                                                                                                                                                                                        span.addEventListener("mouseout", () => {
                                                                                                                                                                                                                    span.style.textDecoration = "none";
                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                    articles.forEach(article => {
                                                                                                                                                                                                                                            article.addEventListener("click", () => {
                                                                                                                                                                                                                                                        articles.forEach(a => a.style.border = "none");
                                                                                                                                                                                                                                                                    article.style.border = "2px solid #3498db";
                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                    figures.forEach(figure => {
                                                                                                                                                                                                                                                                                            figure.addEventListener("mouseover", () => {
                                                                                                                                                                                                                                                                                                        figure.style.transform = "scale(1.03)";
                                                                                                                                                                                                                                                                                                                    figure.style.transition = "0.3s";
                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                    figure.addEventListener("mouseout", () => {
                                                                                                                                                                                                                                                                                                                                                figure.style.transform = "scale(1)";
                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                images.forEach(img => {
                                                                                                                                                                                                                                                                                                                                                                        img.addEventListener("mouseover", () => {
                                                                                                                                                                                                                                                                                                                                                                                    img.style.opacity = "0.9";
                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                    img.addEventListener("mouseout", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                img.style.opacity = "1";
                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                tables.forEach(table => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        table.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    table.style.backgroundColor = "#ecf0f1";
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lists.forEach(list => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            list.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list.style.color = "#2980b9";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (aside) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const dicas = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Organize um horário fixo de estudos",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Faça pausas regulares",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Revise o conteúdo semanalmente",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Evite distrações durante o estudo"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let indice = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const paragrafo = aside.querySelector("p");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (paragrafo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paragrafo.textContent = dicas[indice];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            indice = (indice + 1) % dicas.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 4000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (footer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                footer.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            footer.innerHTML = "<span>Plano de Estudos</span> - JavaScript ativo";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
})