// ==== DADOS DO BLOG MPB ====
const dadosMPB = [
  {
      nome: "Elis Regina",
          musica: "Como Nossos Pais",
              descricao: "Elis Regina foi uma das maiores vozes da MPB. Seu talento e emoção marcaram gerações, e suas interpretações são até hoje referência.",
                  imagem: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Elis_Regina_1979.jpg"
                    },
                      {
                          nome: "Gal Costa",
                              musica: "Baby",
                                  descricao: "Gal Costa foi um dos maiores ícones do Tropicalismo. Dona de uma voz única, sua presença no palco encantava multidões.",
                                      imagem: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Gal_Costa_2022.jpg"
                                        },
                                          {
                                              nome: "Marisa Monte",
                                                  musica: "Ainda Bem",
                                                      descricao: "Marisa Monte é conhecida pela suavidade de sua voz e pelas letras poéticas. Sua música mistura MPB, pop e samba.",
                                                          imagem: "https://upload.wikimedia.org/wikipedia/commons/7/76/Marisa_Monte_2012.jpg"
                                                            },
                                                              {
                                                                  nome: "Maria Bethânia",
                                                                      musica: "Negue",
                                                                          descricao: "Irmã de Caetano Veloso, Maria Bethânia tem uma voz marcante e um estilo teatral, sendo uma das maiores intérpretes do Brasil.",
                                                                              imagem: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Maria_Beth%C3%A2nia_2015.jpg"
                                                                                },
                                                                                  {
                                                                                      nome: "Adriana Calcanhotto",
                                                                                          musica: "Devolva-me",
                                                                                              descricao: "Adriana Calcanhotto é cantora e compositora, com letras que unem sensibilidade e inteligência. Sua obra transita entre o popular e o experimental.",
                                                                                                  imagem: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Adriana_Calcanhotto_2018.jpg"
                                                                                                    },
                                                                                                      {
                                                                                                          nome: "Céu",
                                                                                                              musica: "Malemolência",
                                                                                                                  descricao: "Céu representa a nova geração da MPB, com um som moderno que mistura samba, reggae e pop alternativo.",
                                                                                                                      imagem: "https://upload.wikimedia.org/wikipedia/commons/1/18/C%C3%A9u_-_2016.jpg"
                                                                                                                        }
                                                                                                                        ];

                                                                                                                        // ==== FUNÇÃO DE PESQUISA ====
                                                                                                                        function buscarConteudo() {
                                                                                                                          const termo = document.getElementById("pesquisa").value.toLowerCase().trim();
                                                                                                                            const resultado = document.getElementById("resultado");
                                                                                                                              resultado.innerHTML = ""; // Limpa antes de mostrar os novos resultados

                                                                                                                                // Se o campo estiver vazio
                                                                                                                                  if (termo === "") {
                                                                                                                                      resultado.innerHTML = "<p>Digite o nome da cantora ou música 🎵</p>";
                                                                                                                                          return;
                                                                                                                                            }

                                                                                                                                              // Procura nas informações
                                                                                                                                                const encontrados = dadosMPB.filter(item =>
                                                                                                                                                    item.nome.toLowerCase().includes(termo) ||
                                                                                                                                                        item.musica.toLowerCase().includes(termo)
                                                                                                                                                          );

                                                                                                                                                            // Se encontrar resultados
                                                                                                                                                              if (encontrados.length > 0) {
                                                                                                                                                                  resultado.innerHTML = `<h3>🔍 Resultado da Pesquisa:</h3>`;
                                                                                                                                                                      
                                                                                                                                                                          encontrados.forEach(item => {
                                                                                                                                                                                const card = document.createElement("div");
                                                                                                                                                                                      card.classList.add("resultado-card");
                                                                                                                                                                                            card.innerHTML = `
                                                                                                                                                                                                    <img src="${item.imagem}" alt="${item.nome}">
                                                                                                                                                                                                            <h4>${item.nome}</h4>
                                                                                                                                                                                                                    <p><strong>Música:</strong> ${item.musica}</p>
                                                                                                                                                                                                                            <p>${item.descricao}</p>
                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                        resultado.appendChild(card);
                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                  resultado.innerHTML = "<p>Nenhum resultado encontrado 😔</p>";
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                    // ==== MELHORIA: ativar a pesquisa ao pressionar Enter ====
                                                                                                                                                                                                                                                    document.getElementById("pesquisa").addEventListener("keypress", function(e) {
                                                                                                                                                                                                                                                      if (e.key === "Enter") {
                                                                                                                                                                                                                                                          buscarConteudo();
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                           // ==== BANCO DE DADOS DAS CANTORAS E MÚSICAS ====
                                                                                                                                                                                                                                           const dadosMPB = [
                                                                                                                                                                                                                                             {
                                                                                                                                                                                                                                                 nome: "Elis Regina",
                                                                                                                                                                                                                                                     musica: "Como Nossos Pais",
                                                                                                                                                                                                                                                         descricao: "Elis Regina é considerada uma das maiores vozes do Brasil. Suas interpretações intensas marcaram gerações e continuam inspirando artistas.",
                                                                                                                                                                                                                                                             imagem: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Elis_Regina_1979.jpg"
                                                                                                                                                                                                                                                               },
                                                                                                                                                                                                                                                                 {
                                                                                                                                                                                                                                                                     nome: "Gal Costa",
                                                                                                                                                                                                                                                                         musica: "Baby",
                                                                                                                                                                                                                                                                             descricao: "Gal Costa foi um dos ícones do tropicalismo e da MPB. Sua voz e presença de palco conquistaram o público por décadas.",
                                                                                                                                                                                                                                                                                 imagem: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Gal_Costa_2022.jpg"
                                                                                                                                                                                                                                                                                   },
                                                                                                                                                                                                                                                                                     {
                                                                                                                                                                                                                                                                                         nome: "Marisa Monte",
                                                                                                                                                                                                                                                                                             musica: "Ainda Bem",
                                                                                                                                                                                                                                                                                                 descricao: "Marisa Monte mistura poesia, MPB e pop, sendo uma das artistas mais premiadas e respeitadas da música brasileira.",
                                                                                                                                                                                                                                                                                                     imagem: "https://upload.wikimedia.org/wikipedia/commons/7/76/Marisa_Monte_2012.jpg"
                                                                                                                                                                                                                                                                                                       },
                                                                                                                                                                                                                                                                                                         {
                                                                                                                                                                                                                                                                                                             nome: "Maria Bethânia",
                                                                                                                                                                                                                                                                                                                 musica: "Negue",
                                                                                                                                                                                                                                                                                                                     descricao: "Com uma voz marcante e interpretação teatral, Maria Bethânia é uma das figuras mais importantes da música brasileira.",
                                                                                                                                                                                                                                                                                                                         imagem: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Maria_Beth%C3%A2nia_2015.jpg"
                                                                                                                                                                                                                                                                                                                           },
                                                                                                                                                                                                                                                                                                                             {
                                                                                                                                                                                                                                                                                                                                 nome: "Adriana Calcanhotto",
                                                                                                                                                                                                                                                                                                                                     musica: "Devolva-me",
                                                                                                                                                                                                                                                                                                                                         descricao: "Cantora e compositora talentosa, Adriana Calcanhotto combina lirismo e leveza em suas músicas, transitando entre o pop e o poético.",
                                                                                                                                                                                                                                                                                                                                             imagem: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Adriana_Calcanhotto_2018.jpg"
                                                                                                                                                                                                                                                                                                                                               },
                                                                                                                                                                                                                                                                                                                                                 {
                                                                                                                                                                                                                                                                                                                                                     nome: "Céu",
                                                                                                                                                                                                                                                                                                                                                         musica: "Malemolência",
                                                                                                                                                                                                                                                                                                                                                             descricao: "Céu representa a nova geração da MPB, misturando samba, reggae e sons eletrônicos com um estilo moderno e original.",
                                                                                                                                                                                                                                                                                                                                                                 imagem: "https://upload.wikimedia.org/wikipedia/commons/1/18/C%C3%A9u_-_2016.jpg"
                                                                                                                                                                                                                                                                                                                                                                   },
                                                                                                                                                                                                                                                                                                                                                                     {
                                                                                                                                                                                                                                                                                                                                                                         nome: "Vanessa da Mata",
                                                                                                                                                                                                                                                                                                                                                                             musica: "Ai, Ai, Ai",
                                                                                                                                                                                                                                                                                                                                                                                 descricao: "Vanessa da Mata traz em suas músicas o romantismo e a alegria da MPB moderna, com letras cheias de sentimento.",
                                                                                                                                                                                                                                                                                                                                                                                     imagem: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Vanessa_da_Mata_-_2016.jpg"
                                                                                                                                                                                                                                                                                                                                                                                       },
                                                                                                                                                                                                                                                                                                                                                                                         {
                                                                                                                                                                                                                                                                                                                                                                                             nome: "Ana Carolina",
                                                                                                                                                                                                                                                                                                                                                                                                 musica: "Quem de Nós Dois",
                                                                                                                                                                                                                                                                                                                                                                                                     descricao: "Ana Carolina é conhecida por sua voz grave e composições intensas, que retratam o amor e a vida de forma sincera.",
                                                                                                                                                                                                                                                                                                                                                                                                         imagem: "https://upload.wikimedia.org/wikipedia/commons/3/30/Ana_Carolina_2019.jpg"
                                                                                                                                                                                                                                                                                                                                                                                                           },
                                                                                                                                                                                                                                                                                                                                                                                                             {
                                                                                                                                                                                                                                                                                                                                                                                                                 nome: "Roberta Campos",
                                                                                                                                                                                                                                                                                                                                                                                                                     musica: "De Janeiro a Janeiro",
                                                                                                                                                                                                                                                                                                                                                                                                                         descricao: "Roberta Campos tem um estilo suave e delicado, com letras românticas e uma voz doce que encanta os fãs da MPB atual.",
                                                                                                                                                                                                                                                                                                                                                                                                                             imagem: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Roberta_Campos_2016.jpg"
                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                               ];

                                                                                                                                                                                                                                                                                                                                                                                                                               // ==== FUNÇÃO PRINCIPAL DE PESQUISA ====
                                                                                                                                                                                                                                                                                                                                                                                                                               function buscarConteudo() {
                                                                                                                                                                                                                                                                                                                                                                                                                                 const termo = document.getElementById("pesquisa").value.toLowerCase().trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                   const resultado = document.getElementById("resultado");
                                                                                                                                                                                                                                                                                                                                                                                                                                     resultado.innerHTML = ""; // Limpa resultados anteriores

                                                                                                                                                                                                                                                                                                                                                                                                                                       // Verifica se o campo está vazio
                                                                                                                                                                                                                                                                                                                                                                                                                                         if (termo === "") {
                                                                                                                                                                                                                                                                                                                                                                                                                                             resultado.innerHTML = "<p>Digite o nome da cantora ou música 🎶</p>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                 return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Filtra resultados com base no termo
                                                                                                                                                                                                                                                                                                                                                                                                                                                       const encontrados = dadosMPB.filter(item =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                           item.nome.toLowerCase().includes(termo) ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                               item.musica.toLowerCase().includes(termo)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Exibe os resultados encontrados
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (encontrados.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         resultado.innerHTML = `<h3>🔍 Resultados encontrados:</h3>`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                             encontrados.forEach(item => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const card = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         card.classList.add("resultado-card");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               card.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <img src="${item.imagem}" alt="${item.nome}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <h4>${item.nome}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <p><strong>Música:</strong> ${item.musica}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <p>${item.descricao}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           resultado.appendChild(card);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Caso não encontre nada
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         resultado.innerHTML = "<p>Nenhum resultado encontrado 😔</p>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // ==== ATIVA PESQUISA AO PRESSIONAR ENTER ====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           document.getElementById("pesquisa").addEventListener("keypress", function(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (e.key === "Enter") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 buscarConteudo();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    