const startButton = document.getElementById('start-btn');
const nextButton = document.getElementById('next-btn');
const questionContainerElement = document.getElementById('question-container');
const questionElement = document.getElementById('question');
const answerButtonsElement = document.getElementById('answer-buttons');

let shuffledQuestions, currentQuestionIndex;

// Event Listeners
startButton.addEventListener('click', startGame);
nextButton.addEventListener('click', () => {
    currentQuestionIndex++;
        setNextQuestion();
        });

        // As perguntas do quiz
        const questions = [
            {
                    question: 'Qual a capital do Brasil?',
                            answers: [
                                        { text: 'Rio de Janeiro', correct: false },
                                                    { text: 'São Paulo', correct: false },
                                                                { text: 'Brasília', correct: true },
                                                                            { text: 'Salvador', correct: false }
                                                                                    ]
                                                                                        },
                                                                                            {
                                                                                                    question: 'Em que ano o Brasil foi descoberto?',
                                                                                                            answers: [
                                                                                                                        { text: '1500', correct: true },
                                                                                                                                    { text: '1822', correct: false },
                                                                                                                                                { text: '1900', correct: false },
                                                                                                                                                            { text: '1492', correct: false }
                                                                                                                                                                    ]
                                                                                                                                                                        },
                                                                                                                                                                            {
                                                                                                                                                                                    question: 'Qual o maior rio do Brasil?',
                                                                                                                                                                                            answers: [
                                                                                                                                                                                                        { text: 'Rio Paraná', correct: false },
                                                                                                                                                                                                                    { text: 'Rio Amazonas', correct: true },
                                                                                                                                                                                                                                { text: 'Rio São Francisco', correct: false },
                                                                                                                                                                                                                                            { text: 'Rio Tietê', correct: false }
                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                    question: 'Qual a cor da bandeira do Brasil que representa as matas?',
                                                                                                                                                                                                                                                                            answers: [
                                                                                                                                                                                                                                                                                        { text: 'Azul', correct: false },
                                                                                                                                                                                                                                                                                                    { text: 'Branco', correct: false },
                                                                                                                                                                                                                                                                                                                { text: 'Amarelo', correct: false },
                                                                                                                                                                                                                                                                                                                            { text: 'Verde', correct: true }
                                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                        // Função para iniciar o jogo
                                                                                                                                                                                                                                                                                                                                        function startGame() {
                                                                                                                                                                                                                                                                                                                                            startButton.classList.add('hide');
                                                                                                                                                                                                                                                                                                                                                // Mistura as perguntas aleatoriamente
                                                                                                                                                                                                                                                                                                                                                    shuffledQuestions = questions.sort(() => Math.random() - .5);
                                                                                                                                                                                                                                                                                                                                                        currentQuestionIndex = 0;
                                                                                                                                                                                                                                                                                                                                                            questionContainerElement.classList.remove('hide');
                                                                                                                                                                                                                                                                                                                                                                setNextQuestion();
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                // Função para definir a próxima pergunta
                                                                                                                                                                                                                                                                                                                                                                function setNextQuestion() {
                                                                                                                                                                                                                                                                                                                                                                    resetState();
                                                                                                                                                                                                                                                                                                                                                                        showQuestion(shuffledQuestions[currentQuestionIndex]);
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        // Função para exibir a pergunta e opções
                                                                                                                                                                                                                                                                                                                                                                        function showQuestion(question) {
                                                                                                                                                                                                                                                                                                                                                                            questionElement.innerText = question.question;
                                                                                                                                                                                                                                                                                                                                                                                question.answers.forEach(answer => {
                                                                                                                                                                                                                                                                                                                                                                                        const button = document.createElement('button');
                                                                                                                                                                                                                                                                                                                                                                                                button.innerText = answer.text;
                                                                                                                                                                                                                                                                                                                                                                                                        button.classList.add('btn');
                                                                                                                                                                                                                                                                                                                                                                                                                if (answer.correct) {
                                                                                                                                                                                                                                                                                                                                                                                                                            // Adiciona um data attribute para identificar a resposta correta
                                                                                                                                                                                                                                                                                                                                                                                                                                        button.dataset.correct = answer.correct;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        button.addEventListener('click', selectAnswer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                answerButtonsElement.appendChild(button);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Função para redefinir o estado dos botões
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function resetState() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        clearStatusClass(document.body);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nextButton.classList.add('hide');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while (answerButtonsElement.firstChild) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        answerButtonsElement.removeChild(answerButtonsElement.firstChild);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Função para selecionar uma resposta
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function selectAnswer(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const selectedButton = e.target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const correct = selectedButton.dataset.correct === 'true';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setStatusClass(document.body, correct);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Array.from(answerButtonsElement.children).forEach(button => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setStatusClass(button, button.dataset.correct === 'true');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            button.disabled = true; // Desabilita todos os botões após a seleção
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Mostra o botão "Próxima Pergunta" ou "Reiniciar"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (shuffledQuestions.length > currentQuestionIndex + 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextButton.classList.remove('hide');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            startButton.innerText = 'Reiniciar';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    startButton.classList.remove('hide');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Função para aplicar classes de status (correto/errado)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function setStatusClass(element, correct) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            clearStatusClass(element);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (correct) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        element.classList.add('correct');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    element.classList.add('wrong');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Função para limpar as classes de status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function clearStatusClass(element) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            element.classList.remove('correct');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                element.classList.remove('wrong');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                