// script.js - funcionalidades para o Plano de Estudo
// - Relógio em tempo real
// - Mostrar / esconder dicas
// - Painel Pomodoro (start / pause / reset)
// - Salvar meta semanal no localStorage
// Works even if HTML lacks specific IDs (creates controls dynamically).

(function () {
  // ---------- UTILIDADES ----------
    function el(selector) { return document.querySelector(selector); }
      function create(tag, props = {}, parent = document.body) {
          const node = document.createElement(tag);
              Object.entries(props).forEach(([k, v]) => {
                    if (k === "text") node.textContent = v;
                          else if (k === "html") node.innerHTML = v;
                                else node.setAttribute(k, v);
                                    });
                                        parent.appendChild(node);
                                            return node;
                                              }

                                                // ---------- CRIA / ENCONTRA O PAINEL DE CONTROLE ----------
                                                  let aside = el("aside");
                                                    if (!aside) {
                                                        // Se não houver aside, cria um controle no final do body
                                                            aside = create("aside", { id: "study-aside" });
                                                                aside.style.margin = "20px";
                                                                    aside.style.padding = "12px";
                                                                        aside.style.borderRadius = "8px";
                                                                            aside.style.boxShadow = "0 2px 6px rgba(0,0,0,0.06)";
                                                                                aside.style.background = "#fff7ec";
                                                                                  }

                                                                                    const panel = create("div", { id: "study-panel" }, aside);
                                                                                      panel.style.display = "flex";
                                                                                        panel.style.flexDirection = "column";
                                                                                          panel.style.gap = "10px";

                                                                                            // ---------- RELÓGIO ----------
                                                                                              const clockWrap = create("div", {}, panel);
                                                                                                create("strong", { text: "Relógio: " }, clockWrap);
                                                                                                  const clock = create("span", { id: "relogio", text: "--:--:--" }, clockWrap);

                                                                                                    function updateClock() {
                                                                                                        const now = new Date();
                                                                                                            const hh = String(now.getHours()).padStart(2, "0");
                                                                                                                const mm = String(now.getMinutes()).padStart(2, "0");
                                                                                                                    const ss = String(now.getSeconds()).padStart(2, "0");
                                                                                                                        clock.textContent = `${hh}:${mm}:${ss}`;
                                                                                                                          }
                                                                                                                            updateClock();
                                                                                                                              setInterval(updateClock, 1000);

                                                                                                                                // ---------- MOSTRAR / ESCONDER DICAS ----------
                                                                                                                                  // tenta achar elemento com id 'caixa-dicas' (mencionado em exemplos anteriores)
                                                                                                                                    let dicasBox = el("#caixa-dicas") || el("#dicas") || el("aside") || null;

                                                                                                                                      // cria uma área de dicas se não existir
                                                                                                                                        if (!dicasBox || dicasBox === aside) {
                                                                                                                                            // se aside for usado como painel, cria uma sub-box de dicas no painel (para não sobrescrever)
                                                                                                                                                if (dicasBox === aside) dicasBox = null;
                                                                                                                                                    if (!dicasBox) {
                                                                                                                                                          dicasBox = create("div", { id: "caixa-dicas" }, panel);
                                                                                                                                                                dicasBox.innerHTML = `
                                                                                                                                                                        <h4 style="margin:0 0 6px 0">Dicas Rápidas</h4>
                                                                                                                                                                                <ul style="margin:6px 0 0 18px;padding:0;color:#333">
                                                                                                                                                                                          <li>Estude em blocos (Pomodoro).</li>
                                                                                                                                                                                                    <li>Revisões semanais ajudam a fixar.</li>
                                                                                                                                                                                                              <li>Organize seu material antes de começar.</li>
                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                            `;
                                                                                                                                                                                                                                  dicasBox.style.background = "#fff";
                                                                                                                                                                                                                                        dicasBox.style.padding = "8px";
                                                                                                                                                                                                                                              dicasBox.style.borderRadius = "6px";
                                                                                                                                                                                                                                                    dicasBox.style.boxShadow = "0 1px 4px rgba(0,0,0,0.04)";
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                            const btnToggleDicas = create("button", { id: "btn-toggle-dicas", text: "Mostrar/Ocultar Dicas" }, panel);
                                                                                                                                                                                                                                                              btnToggleDicas.style.cursor = "pointer";
                                                                                                                                                                                                                                                                btnToggleDicas.onclick = function () {
                                                                                                                                                                                                                                                                    if (!dicasBox) return;
                                                                                                                                                                                                                                                                        if (dicasBox.style.display === "none") dicasBox.style.display = "";
                                                                                                                                                                                                                                                                            else dicasBox.style.display = "none";
                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                // ---------- META SEMANAL (localStorage) ----------
                                                                                                                                                                                                                                                                                  const goalWrap = create("div", {}, panel);
                                                                                                                                                                                                                                                                                    create("label", { text: "Meta semanal (horas): ", for: "weeklyGoal" }, goalWrap);
                                                                                                                                                                                                                                                                                      const goalInput = create("input", { id: "weeklyGoal", type: "number", min: "0", value: localStorage.getItem("weeklyGoal") || "5" }, goalWrap);
                                                                                                                                                                                                                                                                                        goalInput.style.width = "60px";
                                                                                                                                                                                                                                                                                          const saveGoalBtn = create("button", { text: "Salvar Meta" }, goalWrap);
                                                                                                                                                                                                                                                                                            saveGoalBtn.style.marginLeft = "8px";
                                                                                                                                                                                                                                                                                              saveGoalBtn.onclick = () => {
                                                                                                                                                                                                                                                                                                  const val = Number(goalInput.value);
                                                                                                                                                                                                                                                                                                      if (isNaN(val) || val < 0) {
                                                                                                                                                                                                                                                                                                            alert("Digite um número válido para a meta (horas).");
                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                          localStorage.setItem("weeklyGoal", String(val));
                                                                                                                                                                                                                                                                                                                              alert("Meta salva: " + val + " horas/semana");
                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                  // ---------- POMODORO ----------
                                                                                                                                                                                                                                                                                                                                    const pomWrap = create("div", {}, panel);
                                                                                                                                                                                                                                                                                                                                      pomWrap.style.background = "#fff";
                                                                                                                                                                                                                                                                                                                                        pomWrap.style.padding = "8px";
                                                                                                                                                                                                                                                                                                                                          pomWrap.style.borderRadius = "6px";
                                                                                                                                                                                                                                                                                                                                            pomWrap.style.boxShadow = "0 1px 4px rgba(0,0,0,0.03)";

                                                                                                                                                                                                                                                                                                                                              create("h4", { text: "Pomodoro" }, pomWrap);

                                                                                                                                                                                                                                                                                                                                                const cfg = create("div", {}, pomWrap);
                                                                                                                                                                                                                                                                                                                                                  cfg.style.display = "flex";
                                                                                                                                                                                                                                                                                                                                                    cfg.style.gap = "8px";
                                                                                                                                                                                                                                                                                                                                                      cfg.style.alignItems = "center";

                                                                                                                                                                                                                                                                                                                                                        create("label", { text: "Estudo (min): " }, cfg);
                                                                                                                                                                                                                                                                                                                                                          const studyInput = create("input", { type: "number", value: "25", min: "1" }, cfg);
                                                                                                                                                                                                                                                                                                                                                            studyInput.style.width = "60px";

                                                                                                                                                                                                                                                                                                                                                              create("label", { text: "Pausa (min): " }, cfg);
                                                                                                                                                                                                                                                                                                                                                                const breakInput = create("input", { type: "number", value: "5", min: "1" }, cfg);
                                                                                                                                                                                                                                                                                                                                                                  breakInput.style.width = "60px";

                                                                                                                                                                                                                                                                                                                                                                    const display = create("div", { text: "00:00", id: "pomodoro-display" }, pomWrap);
                                                                                                                                                                                                                                                                                                                                                                      display.style.fontWeight = "700";
                                                                                                                                                                                                                                                                                                                                                                        display.style.fontSize = "1.15rem";
                                                                                                                                                                                                                                                                                                                                                                          display.style.marginTop = "6px";

                                                                                                                                                                                                                                                                                                                                                                            const controls = create("div", {}, pomWrap);
                                                                                                                                                                                                                                                                                                                                                                              controls.style.display = "flex";
                                                                                                                                                                                                                                                                                                                                                                                controls.style.gap = "8px";
                                                                                                                                                                                                                                                                                                                                                                                  controls.style.marginTop = "6px";

                                                                                                                                                                                                                                                                                                                                                                                    const startBtn = create("button", { text: "Start" }, controls);
                                                                                                                                                                                                                                                                                                                                                                                      const pauseBtn = create("button", { text: "Pause" }, controls);
                                                                                                                                                                                                                                                                                                                                                                                        const resetBtn = create("button", { text: "Reset" }, controls);

                                                                                                                                                                                                                                                                                                                                                                                          let pomTimer = null;
                                                                                                                                                                                                                                                                                                                                                                                            let remaining = 0; // seconds
                                                                                                                                                                                                                                                                                                                                                                                              let mode = "study"; // or 'break'
                                                                                                                                                                                                                                                                                                                                                                                                let running = false;

                                                                                                                                                                                                                                                                                                                                                                                                  function formatTime(s) {
                                                                                                                                                                                                                                                                                                                                                                                                      const mm = String(Math.floor(s / 60)).padStart(2, "0");
                                                                                                                                                                                                                                                                                                                                                                                                          const ss = String(s % 60).padStart(2, "0");
                                                                                                                                                                                                                                                                                                                                                                                                              return `${mm}:${ss}`;
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                  function startPomodoro() {
                                                                                                                                                                                                                                                                                                                                                                                                                      if (running) return;
                                                                                                                                                                                                                                                                                                                                                                                                                          const studySec = Math.max(1, Number(studyInput.value)) * 60;
                                                                                                                                                                                                                                                                                                                                                                                                                              const breakSec = Math.max(1, Number(breakInput.value)) * 60;

                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!pomTimer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        mode = "study";
                                                                                                                                                                                                                                                                                                                                                                                                                                              remaining = studySec;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      running = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                          pomTimer = setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (remaining <= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // switch mode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (mode === "study") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          mode = "break";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    remaining = breakSec;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display.style.color = "#1b7a1b";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash(document.body, "#e8ffe8");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alert("Pausa iniciada! Descanse " + (breakSec/60) + " minuto(s).");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mode = "study";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              remaining = studySec;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display.style.color = "#e65c00";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flash(document.body, "#fff3e6");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Período de estudo iniciado! Foque " + (studySec/60) + " minuto(s).");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  remaining -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          display.textContent = `${mode === "study" ? "Estudo " : "Pausa  "} - ${formatTime(remaining)}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function pausePomodoro() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (pomTimer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  clearInterval(pomTimer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pomTimer = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              running = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function resetPomodoro() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pausePomodoro();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              pomTimer = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  remaining = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display.textContent = "00:00";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          display.style.color = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              startBtn.onclick = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  startPomodoro();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pauseBtn.onclick = () => pausePomodoro();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        resetBtn.onclick = () => resetPomodoro();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // small flash helper
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function flash(elm, color) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const original = elm.style.backgroundColor;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elm.style.transition = "background-color 0.3s";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elm.style.backgroundColor = color;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => { elm.style.backgroundColor = original; }, 350);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ---------- DICA: salvar preferências (ex: durações) no unload ----------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.addEventListener("beforeunload", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      localStorage.setItem("pom_study", String(studyInput.value));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          localStorage.setItem("pom_break", String(breakInput.value));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // recuperar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const savedStudy = localStorage.getItem("pom_study");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const savedBreak = localStorage.getItem("pom_break");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (savedStudy) studyInput.value = savedStudy;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (savedBreak) breakInput.value = savedBreak;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ---------- BOAS-VINDAS (apenas uma vez por sessão) ----------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!sessionStorage.getItem("welcomeSeen")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert("Bem-vindo(a)! Use o painel para controlar seu estudo (Pomodoro, dicas, meta).");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 400);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sessionStorage.setItem("welcomeSeen", "1");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ---------- Acessibilidade: atalhos de teclado ----------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.addEventListener("keydown", (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Ctrl+M -> mostrar/ocultar dicas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (e.ctrlKey && (e.key === "m" || e.key === "M")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btnToggleDicas.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Ctrl+P -> start/pause pomodoro
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (e.ctrlKey && (e.key === "p" || e.key === "P")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (running) pauseBtn.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else startBtn.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ---------- Fim do IIFE ----------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })();