// script.js — upload + render do feed com span, h2, h3, p, nav, a, header, main, img, h3, h2, p etc.

(() => {
  const fileInput = document.getElementById('fileInput');
    const openUpload = document.getElementById('openUpload');
      const feed = document.getElementById('feed');
        const previewImages = document.getElementById('previewImages');

          const LS_KEY = 'instalite_posts_v2';

            function loadPosts(){
                const raw = localStorage.getItem(LS_KEY);
                    if(!raw) return [];
                        try { return JSON.parse(raw); } catch (e){ console.warn('Erro parse posts', e); return []; }
                          }
                            function savePosts(posts){ localStorage.setItem(LS_KEY, JSON.stringify(posts)); }

                              function renderFeed(){
                                  feed.innerHTML = '';
                                      const posts = loadPosts();
                                          if(posts.length === 0){
                                                const empty = document.createElement('div');
                                                      empty.className = 'empty';
                                                            empty.innerHTML = '<p>Nenhum post ainda — crie um usando o botão +</p>';
                                                                  feed.appendChild(empty);
                                                                        return;
                                                                            }
                                                                                // mais novo primeiro
                                                                                    posts.sort((a,b) => b.createdAt - a.createdAt);
                                                                                        posts.forEach(p => feed.appendChild(createPostElement(p)));
                                                                                          }

                                                                                            function createPostElement(post){
                                                                                                const article = document.createElement('article');
                                                                                                    article.className = 'post';

                                                                                                        // header (header tag is in HTML page top; aqui é o cabeçalho do post)
                                                                                                            const postHeader = document.createElement('div');
                                                                                                                postHeader.className = 'post-header';
                                                                                                                    postHeader.innerHTML = `
                                                                                                                          <div class="avatar">GS</div>
                                                                                                                                <div style="flex:1">
                                                                                                                                        <span class="post-user" title="${post.username}">${post.username}</span>
                                                                                                                                                <div class="post-meta"><span class="post-date">${new Date(post.createdAt).toLocaleString()}</span></div>
                                                                                                                                                      </div>
                                                                                                                                                          `;

                                                                                                                                                              // imagem
                                                                                                                                                                  const imgWrap = document.createElement('div');
                                                                                                                                                                      imgWrap.className = 'image-wrap';
                                                                                                                                                                          const img = document.createElement('img');
                                                                                                                                                                              img.alt = post.caption || 'Imagem do post';
                                                                                                                                                                                  img.src = post.imageData;
                                                                                                                                                                                      img.loading = 'lazy';
                                                                                                                                                                                          imgWrap.appendChild(img);

                                                                                                                                                                                              // actions
                                                                                                                                                                                                  const actions = document.createElement('div');
                                                                                                                                                                                                      actions.className = 'actions';
                                                                                                                                                                                                          // like button (com span para contagem)
                                                                                                                                                                                                              actions.innerHTML = `
                                                                                                                                                                                                                    <button class="action like-btn" aria-label="Curtir">♡</button>
                                                                                                                                                                                                                          <button class="action comment-btn" aria-label="Comentar">💬</button>
                                                                                                                                                                                                                                <span class="likes-count" aria-live="polite"><span class="likes-span">${post.likes || 0}</span> curtidas</span>
                                                                                                                                                                                                                                    `;

                                                                                                                                                                                                                                        // caption (usa span dentro de p)
                                                                                                                                                                                                                                            const caption = document.createElement('div');
                                                                                                                                                                                                                                                caption.className = 'caption';
                                                                                                                                                                                                                                                    const captionP = document.createElement('p');
                                                                                                                                                                                                                                                        const captionUser = document.createElement('span');
                                                                                                                                                                                                                                                            captionUser.className = 'caption-user';
                                                                                                                                                                                                                                                                captionUser.textContent = post.username;
                                                                                                                                                                                                                                                                    const captionText = document.createElement('span');
                                                                                                                                                                                                                                                                        captionText.className = 'caption-text';
                                                                                                                                                                                                                                                                            captionText.textContent = ' ' + (post.caption || '');
                                                                                                                                                                                                                                                                                captionP.appendChild(captionUser);
                                                                                                                                                                                                                                                                                    captionP.appendChild(captionText);
                                                                                                                                                                                                                                                                                        caption.appendChild(captionP);

                                                                                                                                                                                                                                                                                            article.appendChild(postHeader);
                                                                                                                                                                                                                                                                                                article.appendChild(imgWrap);
                                                                                                                                                                                                                                                                                                    article.appendChild(actions);
                                                                                                                                                                                                                                                                                                        article.appendChild(caption);

                                                                                                                                                                                                                                                                                                            // eventos
                                                                                                                                                                                                                                                                                                                const likeBtn = actions.querySelector('.like-btn');
                                                                                                                                                                                                                                                                                                                    const likesSpan = actions.querySelector('.likes-span');

                                                                                                                                                                                                                                                                                                                        likeBtn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                              const posts = loadPosts();
                                                                                                                                                                                                                                                                                                                                    const p = posts.find(x => x.id === post.id);
                                                                                                                                                                                                                                                                                                                                          if(!p) return;
                                                                                                                                                                                                                                                                                                                                                p.likes = (p.likes || 0) + 1;
                                                                                                                                                                                                                                                                                                                                                      savePosts(posts);
                                                                                                                                                                                                                                                                                                                                                            likesSpan.textContent = p.likes;
                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                    // Clique na imagem abre em nova aba (exemplo com <a>)
                                                                                                                                                                                                                                                                                                                                                                        img.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                              const a = document.createElement('a');
                                                                                                                                                                                                                                                                                                                                                                                    a.href = post.imageData;
                                                                                                                                                                                                                                                                                                                                                                                          a.target = '_blank';
                                                                                                                                                                                                                                                                                                                                                                                                a.rel = 'noopener';
                                                                                                                                                                                                                                                                                                                                                                                                      document.body.appendChild(a);
                                                                                                                                                                                                                                                                                                                                                                                                            a.click();
                                                                                                                                                                                                                                                                                                                                                                                                                  a.remove();
                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                          return article;
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                              // abrir input ao clicar no FAB
                                                                                                                                                                                                                                                                                                                                                                                                                                openUpload.addEventListener('click', () => fileInput.click());

                                                                                                                                                                                                                                                                                                                                                                                                                                  // lidar com arquivos selecionados
                                                                                                                                                                                                                                                                                                                                                                                                                                    fileInput.addEventListener('change', async (ev) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const files = Array.from(ev.target.files || []);
                                                                                                                                                                                                                                                                                                                                                                                                                                            if(!files.length) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                previewImages.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                    for(const f of files){
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const url = URL.createObjectURL(f);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const img = document.createElement('img');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      img.src = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            img.alt = f.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  img.style.maxWidth = '120px';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        img.style.maxHeight = '120px';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              previewImages.appendChild(img);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // confirmar e criar posts (aqui criamos imediatamente)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for(const f of files){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const base64 = await fileToDataURL(f);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const posts = loadPosts();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const newPost = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id: 'p_' + Date.now() + '_' + Math.random().toString(36).slice(2,7),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            username: 'gilderlan Santana',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      imageData: base64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                createdAt: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          likes: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    caption: ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    posts.push(newPost);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            savePosts(posts);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch(err){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('Erro ao ler arquivo', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // limpar e renderizar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fileInput.value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                previewImages.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    renderFeed();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // função utilitária
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function fileToDataURL(file){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const reader = new FileReader();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          reader.onload = () => resolve(reader.result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reader.onerror = () => reject(new Error('Erro ao ler arquivo'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      reader.readAsDataURL(file);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // drag & drop básico na área do preview (opcional)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const uploaderPreview = document.getElementById('uploaderPreview');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ;['dragenter','dragover'].forEach(ev => uploaderPreview.addEventListener(ev, e => { e.preventDefault(); uploaderPreview.classList.add('dragover'); }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ;['dragleave','drop'].forEach(ev => uploaderPreview.addEventListener(ev, e => { e.preventDefault(); uploaderPreview.classList.remove('dragover'); }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      uploaderPreview.addEventListener('drop', e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const dt = e.dataTransfer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(!dt) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const files = Array.from(dt.files || []).filter(f => f.type.startsWith('image/'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if(files.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // preencher input programaticamente não é suportado por segurança, mas podemos processar os arquivos diretamente:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  (async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          previewImages.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for(const f of files){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const url = URL.createObjectURL(f);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const img = document.createElement('img'); img.src = url; img.alt = f.name; img.style.maxWidth='120px'; previewImages.appendChild(img);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for(const f of files){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const base64 = await fileToDataURL(f);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const posts = loadPosts();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    posts.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id: 'p_' + Date.now() + '_' + Math.random().toString(36).slice(2,7),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            username: 'gilderlan Santana',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        imageData: base64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    createdAt: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                likes: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            caption: ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                savePosts(posts);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                previewImages.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderFeed();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // inicializa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderFeed();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // função debug para limpar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window._instalite = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clear: () => { localStorage.removeItem(LS_KEY); renderFeed(); },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    posts: () => loadPosts()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })();