// ===============================
// JavaScript — Feed Blog Pessoal de Viagens
// ===============================

// Simulação de curtidas e comentários

document.addEventListener('DOMContentLoaded', () => {
  const likeButtons = document.querySelectorAll('.controls button:first-child');
    const commentButtons = document.querySelectorAll('.controls button:nth-child(2)');

      // Incrementar curtidas
        likeButtons.forEach(btn => {
            btn.addEventListener('click', () => {
                  let currentLikes = parseInt(btn.textContent.replace(/\D/g, ''));
                        currentLikes++;
                              btn.textContent = `❤️ ${currentLikes}`;
                                    btn.setAttribute('aria-pressed', 'true');
                                        });
                                          });

                                            // Exibir caixa de comentário rápida (simulada)
                                              commentButtons.forEach(btn => {
                                                  btn.addEventListener('click', () => {
                                                        const article = btn.closest('article');
                                                              let commentBox = article.querySelector('.new-comment');
                                                                    if (!commentBox) {
                                                                            commentBox = document.createElement('div');
                                                                                    commentBox.className = 'new-comment';
                                                                                            commentBox.innerHTML = `
                                                                                                      <textarea rows="2" placeholder="Escreva um comentário..." style="width:100%;padding:.5rem;margin-top:.5rem;border-radius:8px;border:1px solid #ddd;"></textarea>
                                                                                                                <button style="margin-top:.5rem;padding:.4rem .8rem;border:none;border-radius:8px;background:#0b8;color:white;cursor:pointer;">Enviar</button>
                                                                                                                        `;
                                                                                                                                article.appendChild(commentBox);

                                                                                                                                        const sendBtn = commentBox.querySelector('button');
                                                                                                                                                sendBtn.addEventListener('click', () => {
                                                                                                                                                          const txt = commentBox.querySelector('textarea').value.trim();
                                                                                                                                                                    if (!txt) return alert('Digite algo antes de enviar.');

                                                                                                                                                                              const commentList = article.querySelector('.comment-list');
                                                                                                                                                                                        const newComment = document.createElement('div');
                                                                                                                                                                                                  newComment.className = 'comment';
                                                                                                                                                                                                            newComment.innerHTML = `
                                                                                                                                                                                                                        <img src="https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=200&q=60" alt="avatar" />
                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                  <strong>Você</strong> <time>${new Date().toLocaleTimeString([], {hour: '2-digit', minute: '2-digit'})}</time>
                                                                                                                                                                                                                                                                <div>${txt}</div>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                      `;
                                                                                                                                                                                                                                                                                                commentList.appendChild(newComment);
                                                                                                                                                                                                                                                                                                          commentBox.remove();
                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                // Simular envio de formulários da sidebar
                                                                                                                                                                                                                                                                                                                                  document.querySelectorAll('form').forEach(form => {
                                                                                                                                                                                                                                                                                                                                      form.addEventListener('submit', e => {
                                                                                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                  alert('Formulário enviado! (Simulação — conecte um backend real).');
                                                                                                                                                                                                                                                                                                                                                        form.reset();
                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                // Busca simulada de posts
                                                                                                                                                                                                                                                                                                                                                                  const searchInput = document.querySelector('#search');
                                                                                                                                                                                                                                                                                                                                                                    if (searchInput) {
                                                                                                                                                                                                                                                                                                                                                                        searchInput.addEventListener('input', () => {
                                                                                                                                                                                                                                                                                                                                                                              const term = searchInput.value.toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                    document.querySelectorAll('article.post').forEach(post => {
                                                                                                                                                                                                                                                                                                                                                                                            const text = post.innerText.toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                    post.style.display = text.includes(term) ? 'block' : 'none';
                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                  // Destaque visual dos links ao rolar (scrollspy simples)
                                                                                                                                                                                                                                                                                                                                                                                                                    const navLinks = document.querySelectorAll('nav a[href^="#"]');
                                                                                                                                                                                                                                                                                                                                                                                                                      const sections = document.querySelectorAll('article');

                                                                                                                                                                                                                                                                                                                                                                                                                        window.addEventListener('scroll', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                            let fromTop = window.scrollY + 100;

                                                                                                                                                                                                                                                                                                                                                                                                                                sections.forEach(section => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      const id = section.getAttribute('id');
                                                                                                                                                                                                                                                                                                                                                                                                                                            const link = document.querySelector(`nav a[href="#${id}"]`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!link) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (section.offsetTop <= fromTop && section.offsetTop + section.offsetHeight > fromTop) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                link.style.textDecoration = 'underline';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              link.style.textDecoration = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });