// =========================
// app.js (ATUALIZADO)
// =========================

// ---------- Imagens (fáceis de editar) ----------
const profilePic = "https://img.freepik.com/fotos-premium/ilustracao-de-jogos-de-computador-de-desktop_691560-5611.jpg?w=360";

const postImg1 = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXOz2x0_GRoKnD7W3ttSeq6qpF2g8j16wguQH6jPLwu5C43kCHpUt9ULAIwZP3xAxRoZQ&usqp=CAU";
const postImg2 = "https://wallpapers.com/images/hd/cool-profile-picture-g3nzxs9mvrwkt7ew.jpg";
const postImg3 = "https://pics.craiyon.com/2023-05-27/2187584bf2304380954a3e8cac2abfa7.webp";
const postImg4 = "https://img.freepik.com/fotos-premium/ilustracao-de-jogos-de-computador-de-desktop_691560-5611.jpg?w=360";

// ===== Dados iniciais (exemplos reutilizando suas imagens) =====
const initialPosts = [
  {
      id: 1,
          user: 'FroJho',
              avatar: postImg1,
                  time: 'há 10 minutos',
                      text: 'Uma arte incrível pra inspirar o feed.',
                          image: postImg1,
                              likes: 12,
                                  comments: [ {user:'Ana',text:'Lindo!'} ]
                                    },
                                      {
                                          id: 2,
                                              user: 'FroJho',
                                                  avatar: postImg2,
                                                      time: 'há 8 minutos',
                                                          text: 'Foto de perfil estilosa que agradei demais.',
                                                              image: postImg2,
                                                                  likes: 8,
                                                                      comments: []
                                                                        },
                                                                          {
                                                                              id: 3,
                                                                                  user: 'FroJho',
                                                                                      avatar: postImg3,
                                                                                          time: 'há 5 minutos',
                                                                                              text: 'Uma ilustração gerada que ficou top.',
                                                                                                  image: postImg3,
                                                                                                      likes: 3,
                                                                                                          comments: []
                                                                                                            },
                                                                                                              {
                                                                                                                  id: 4,
                                                                                                                      user: 'FroJho',
                                                                                                                          avatar: postImg4,
                                                                                                                              time: 'há 2 minutos',
                                                                                                                                  text: 'Repetindo a arte para testes visuais.',
                                                                                                                                      image: postImg4,
                                                                                                                                          likes: 1,
                                                                                                                                              comments: []
                                                                                                                                                }
                                                                                                                                                ];

                                                                                                                                                // --------- Seletores e templates ----------
                                                                                                                                                const feedEl = document.getElementById('feed');
                                                                                                                                                const cardT = document.getElementById('cardTemplate');
                                                                                                                                                const storiesRow = document.getElementById('storiesRow');
                                                                                                                                                const postBtn = document.getElementById('postBtn');
                                                                                                                                                const newPostText = document.getElementById('newPostText');
                                                                                                                                                const imageUrl = document.getElementById('imageUrl');
                                                                                                                                                const profilePanel = document.getElementById('profilePanel');
                                                                                                                                                const openProfile = document.getElementById('openProfile');
                                                                                                                                                const closeProfile = document.getElementById('closeProfile');
                                                                                                                                                const postsCount = document.getElementById('postsCount');
                                                                                                                                                const profilePosts = document.getElementById('profilePosts');

                                                                                                                                                // Usa storage se existir, senão inicial
                                                                                                                                                let posts = JSON.parse(localStorage.getItem('posts_v1')) || initialPosts.slice();

                                                                                                                                                // Atualiza avatar do botão de perfil (na navbar) com sua imagem
                                                                                                                                                if(openProfile) openProfile.src = profilePic;

                                                                                                                                                // ===== stories simples =====
                                                                                                                                                const stories = [
                                                                                                                                                  {name:'Ana',img:'https://i.pravatar.cc/80?img=3'},
                                                                                                                                                    {name:'Lucas',img:'https://i.pravatar.cc/80?img=4'},
                                                                                                                                                      {name:'Mariana',img:'https://i.pravatar.cc/80?img=8'},
                                                                                                                                                        {name:'Pedro',img:'https://i.pravatar.cc/80?img=9'},
                                                                                                                                                          {name:'Você',img:profilePic},
                                                                                                                                                          ];
                                                                                                                                                          function renderStories(){
                                                                                                                                                            storiesRow.innerHTML = '';
                                                                                                                                                              stories.forEach(s=>{
                                                                                                                                                                  const div = document.createElement('div');
                                                                                                                                                                      div.className='story';
                                                                                                                                                                          div.innerHTML = `<img src="${s.img}" alt="${s.name}"><small>${s.name}</small>`;
                                                                                                                                                                              div.onclick = ()=> alert(`Ver story de ${s.name} (simulação).`);
                                                                                                                                                                                  storiesRow.appendChild(div);
                                                                                                                                                                                    });
                                                                                                                                                                                    }
                                                                                                                                                                                    renderStories();

                                                                                                                                                                                    // ===== render do feed =====
                                                                                                                                                                                    function renderAll(){
                                                                                                                                                                                      feedEl.innerHTML = '';
                                                                                                                                                                                        posts.forEach(post => {
                                                                                                                                                                                            const node = cardT.content.cloneNode(true);
                                                                                                                                                                                                const article = node.querySelector('.card');
                                                                                                                                                                                                    article.dataset.id = post.id;

                                                                                                                                                                                                        node.querySelector('.user-img').src = post.avatar || profilePic;
                                                                                                                                                                                                            node.querySelector('.user-name').textContent = post.user;
                                                                                                                                                                                                                node.querySelector('.user-time').textContent = post.time;
                                                                                                                                                                                                                    node.querySelector('.card-text').textContent = post.text;
                                                                                                                                                                                                                        const imgEl = node.querySelector('.card-image');
                                                                                                                                                                                                                            if(post.image){
                                                                                                                                                                                                                                  imgEl.src = post.image;
                                                                                                                                                                                                                                        imgEl.style.display = '';
                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                  imgEl.style.display = 'none';
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                          node.querySelector('.like-count').textContent = post.likes || 0;
                                                                                                                                                                                                                                                              node.querySelector('.comment-count').textContent = (post.comments || []).length;

                                                                                                                                                                                                                                                                  // like
                                                                                                                                                                                                                                                                      const likeBtn = node.querySelector('.like');
                                                                                                                                                                                                                                                                          likeBtn.addEventListener('click', ()=>{
                                                                                                                                                                                                                                                                                toggleLike(post.id, likeBtn);
                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                        // comment toggle
                                                                                                                                                                                                                                                                                            const commentBtn = node.querySelector('.comment');
                                                                                                                                                                                                                                                                                                const commentSec = node.querySelector('.comment-section');
                                                                                                                                                                                                                                                                                                    commentBtn.addEventListener('click', ()=>{
                                                                                                                                                                                                                                                                                                          commentSec.classList.toggle('hidden');
                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                  // render comments
                                                                                                                                                                                                                                                                                                                      const commentsList = node.querySelector('.comments-list');
                                                                                                                                                                                                                                                                                                                          (post.comments || []).forEach(c=>{
                                                                                                                                                                                                                                                                                                                                const cdiv = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                      cdiv.className = 'comment-item';
                                                                                                                                                                                                                                                                                                                                            cdiv.innerHTML = `<img class="avatar-small" src="https://i.pravatar.cc/28?img=11"><div><strong style="font-size:13px">${c.user}</strong><p>${c.text}</p></div>`;
                                                                                                                                                                                                                                                                                                                                                  commentsList.appendChild(cdiv);
                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                          // enviar comentário
                                                                                                                                                                                                                                                                                                                                                              const postCommentBtn = node.querySelector('.post-comment');
                                                                                                                                                                                                                                                                                                                                                                  const commentInput = node.querySelector('.comment-input');
                                                                                                                                                                                                                                                                                                                                                                      postCommentBtn.addEventListener('click', ()=>{
                                                                                                                                                                                                                                                                                                                                                                            const text = commentInput.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                  if(!text) return;
                                                                                                                                                                                                                                                                                                                                                                                        addComment(post.id, {user:'Você', text});
                                                                                                                                                                                                                                                                                                                                                                                              commentInput.value = '';
                                                                                                                                                                                                                                                                                                                                                                                                    renderAll();
                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                            // share
                                                                                                                                                                                                                                                                                                                                                                                                                const shareBtn = node.querySelector('.share');
                                                                                                                                                                                                                                                                                                                                                                                                                    shareBtn.addEventListener('click', ()=>{
                                                                                                                                                                                                                                                                                                                                                                                                                          // tentativa de copiar link (se suportado)
                                                                                                                                                                                                                                                                                                                                                                                                                                const txt = `Confira este post (simulação): ${window.location.href}#post-${post.id}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                      navigator.clipboard?.writeText(txt).then(()=> alert('Link copiado! (simulação)')).catch(()=> alert('Compartilhar (simulação)'));
                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                              feedEl.appendChild(node);
                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                  postsCount.textContent = posts.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    renderProfilePosts();
                                                                                                                                                                                                                                                                                                                                                                                                                                                      localStorage.setItem('posts_v1', JSON.stringify(posts));
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ===== ações =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                      function toggleLike(id, btn){
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const p = posts.find(x=>x.id===id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          if(!p) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            // marca/desmarca (simulação simples)
                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(btn.classList.contains('active')){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  btn.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      p.likes = Math.max(0, p.likes - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            btn.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                p.likes = (p.likes || 0) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    renderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function addComment(id, comment){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const p = posts.find(x=>x.id===id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(!p) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          p.comments = p.comments || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.comments.push(comment);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              renderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // publicar novo post
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              postBtn.addEventListener('click', ()=>{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const text = newPostText.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const img = imageUrl.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(!text && !img){ alert('Escreva algo ou cole uma imagem!'); return; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const newPost = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              user: 'Thamyres',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  avatar: profilePic,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      time: 'agora',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              image: img || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  likes: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      comments: []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          posts.unshift(newPost);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            newPostText.value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              imageUrl.value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                renderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alert('Post publicado! Boa sorte na avaliação 😊');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // open/close profile panel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  openProfile.addEventListener('click', ()=> { profilePanel.setAttribute('aria-hidden','false'); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  closeProfile.addEventListener('click', ()=> { profilePanel.setAttribute('aria-hidden','true'); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('goProfile').addEventListener('click', ()=> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    profilePanel.setAttribute('aria-hidden','false');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // render posts do perfil
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function renderProfilePosts(){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      profilePosts.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        posts.filter(p=>p.user==='Thamyres').forEach(p=>{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const d = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                d.className = 'mini-post';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    d.style.padding='8px';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        d.style.borderBottom='1px solid rgba(255,255,255,0.03)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            d.innerHTML = `<strong>${p.text.slice(0,60)}${p.text.length>60?'...':''}</strong><div style="font-size:12px;color:var(--muted)">${p.time}</div>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                profilePosts.appendChild(d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // theme toggle (dark/light)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const themeToggle = document.getElementById('themeToggle');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const currentTheme = localStorage.getItem('theme_v1');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if(currentTheme === 'light') document.body.classList.add('tema-light');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  themeToggle.textContent = document.body.classList.contains('tema-light') ? '☀️' : '🌙';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  themeToggle.addEventListener('click', ()=>{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.body.classList.toggle('tema-light');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const isLight = document.body.classList.contains('tema-light');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        themeToggle.textContent = isLight ? '☀️' : '🌙';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          localStorage.setItem('theme_v1', isLight ? 'light' : 'dark');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // hamburger para mobile (abre sidebar)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const btnHamburger = document.getElementById('btn-hamburger');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const sidebar = document.getElementById('sidebar');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          btnHamburger.addEventListener('click', ()=>{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(!sidebar) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(sidebar.style.display === 'block') sidebar.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else sidebar.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // render inicial
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                renderAll();